prithvijitguha/MyView

.github/workflows/build.yml, crud.py, models.py, schemas.py
.github/workflow/build.yml - exclude docs build 
cruds.py - added pseudocode for functions 
models.py - removed comment id foreign key from video_library. Added video_id to comments foreign key 
schemas.py  - modified annotations as per models.py
=> updated build.yml to exclude build.yml defined crud pseudocode

static/styles.css, templates/index.html
Added content to index.html
Added styles to styles.css
=> added index html front end and styles

docs/source/contributing_guide_code.rst, docs/source/contributing_guide_docs.rst, docs/source/index.rst
Added contributing guide for docs to docs/source 
Changed name of contributing_guide to contributing_guide_code
Added contributing_guide_docs to index.rst toctree
=> added contributing guide for docs

README.md, crud/crud.py, docs/source/contributing_guide_docs.rst, docs/source/index.rst
Updated readme
Updated docs, toctree depth and venv names in contributing guide 
crud.py: 
- added `authenticate_user` function
- library import order. Updated `db.refresh` functions syntax
- added function docstring for `get_user_by_email`.
- Updated correct attribute for `Comment[comment_video_id]` model
- updated `req_comment_id ` in `update_comment` function
=> updated readme crud models

templates/base.html, templates/login.html, templates/register.html
Added navbar desktop 
Mobile optimization to be done
=> navbar desktop

.github/workflows/build.yml, tests/test_main.py
Changing `pytest` command to `python -m pytest tests/` fixes the issue
=> fixed pytest and github actions

main.py, templates/upload.html
=> improved upload and added type checking for video

main.py, templates/login.html
main.py: 
- rearragned imports from fastapi 
- added login(get and post) functions 
login.html implemented
=> login page implment and function

crud/crud.py, main.py, models/models.py, schemas/schemas.py, utils/utils.py
added video_link attribute to Video in models.py, crud.py, schemas.py
created utils folder containing utils.py with `create_video_name` function
=> added more s3 support

main.py, templates/login.html, templates/register.html, templates/upload.html
Added test function to check if user logged in main.py 
Added html form to register html 
Added register get and post functions
changed html arialabel attributes in other html pages
=> added register html

templates/index.html, templates/upload.html
Added video demonstration to index.html 
Added forms to upload.html
=> added register page

static/script.js, templates/upload.html
Upload.html: added ids to elements
script.js: added autofill features
=> added autofill for upload

README.md, crud/crud.py, main.py, templates/login.html, templates/upload.html
readme.md: added logo 
cud.py: added `authenticate_user_email `function
main.py: added logic to `login` function `post`
login.html: naming changes 
upload.html: naming changes
=> forms improvements

README.md, azure-pipelines.yml
updated readme and azure to avoid readme changes
=> readme and az

.pylintrc, main.py
pylint: ignore todo 
main.py: `upload_file` function added arguments to be considered later added commented out logic uploading thumbnail
=> pylint fix and video improvement

templates/base.html
Added login and register url to navbar of index.html for testing.
WIll be changed to if condition later
=> added register and login url to index.html

.github/workflows/build.yml, README.md, azure-pipelines.yml
=> updated readme

README.md, main.py
`main.py`: improved logic of `register` function. Removed unused `read_user` function
`readme.md`: added azure badge
=> register function 

main.py, tests/test_main.py
main.py: added `read_user` function 
test_main.py: added tests and falek/pylint ignores
=> added read user and tests

main.py, templates/base.html
`main.py`:
added `token` function and `check_current_user` function. 
added template response and context to `login` and `register` function. Added request as a argument to each function
`base.html`: 
added messages to base template.
=> added messages to base template, improved template response for login and register

azure-pipelines.yml, docs/source/index.rst, docs/source/modules.rst
Fixes #46 
docs: Added module page 
azure-pipelines: updated yml to exclude docs changes
=> DOC: updated documentation and az update

.github/workflows/build.yml, main.py, models/models.py, schemas/schemas.py, static/register.js, templates/base.html, templates/register.html
Fixes: 
#60 
#58 
#59 
#55 
.github/build.yml: pylint all directories 
main.py: improved func-docstring for create_user and register. Added logout function 
models.py: added views int attribute to Video 
schemas.py: added view int attribute to Video 
static/register.js(new file): added show password function and validate form on submit
templates/base.html: added authenticate user navbar optional. Logout option 
templates/register.html: added reconfirm password form input and show password button linked to new register.js script
=> ENH: Feature/improve

README.md, azure-pipelines.yml
updated docs status badge in readme
may fix #50
needs tests
=> updated docs badge

main.py, schemas/schemas.py, templates/upload.html
fixes #41
- Added parameters to `upload_file` function 
- Added parameters to `upload_file` function 
- redirect to homepage on success of `upload_file` function
-  removed unused upload thumbnail code, replaced with TODO tag
- For `Video` schema fixed `=` to `:` for video_height, video_width
- default values for `views`, `no_likes`, `no_dislikes` in `Video` schema
- replaced submit button svg with `upload`
=> upload function

main.py, static/upload.js, templates/upload.html
Fixes: #69 
- moved parameters for description and categories in `upload_file` function 
- made description and categories optional arguments, with default as None 
- fixed spacing 
- removed disable. input disabled doesn't allow Form to pick up data. 
- added end of line markers
=> fixed upload issue

.github/contributing.md, .github/pull_request_template.md, .github/workflows/build.yml, azure-pipelines.yml
#56 
added contributing guide 
pull request template 
az and github actions will not ignore all changes to markdown files
=> added new templates

README.md
=> DOC: updated readme

.pre-commit-config.yaml, templates/upload.html
- fixed upload issue, hiding video quality, length form entries.
- Added safety checks for python with pre-commit hook
=> ENH: upload fix

main.py, templates/index.html
a. Added thumbnail serving to homepage
=> added thumbnail image and precommit checks

main.py, templates/index.html, templates/video.html
=> precommit checks

crud/crud.py, main.py, templates/index.html, templates/video.html
=> ENH: Play Video Functionality

main.py, static/upload.js, templates/index.html, templates/upload.html, templates/video.html
=> ENH: setup thumbnails and homepage

static/index.css, static/styles.css, templates/base.html, templates/index.html
=> ENH: Added rounded corners to profile picture in homepage 

templates/index.html
=> ENH: added view count to homepage

templates/base.html
=> BUG: FIxed favicon error 

static/index.css, templates/index.html
=> updated css index

main.py, static/results.css, templates/base.html, templates/results.html
=> added search

templates/index.html, templates/results.html
=> STYLE: style fixes

crud/crud.py, main.py
=> ENH: added view increment

jwt/jwt_utils.py, main.py, templates/video.html
=> ENH: Like and Dislike buttons

static/upload.js
=> BUG: removed extension from file name in upload

static/video.js, templates/video.html
=> ENH: added video.js and like logic to be implemented

crud/crud.py, models/models.py
=> ENH: added like and dislike crud and table 

crud/crud.py, main.py, models/models.py, static/video.js, templates/video.html
=> ENH: Feature/like js

crud/crud.py, main.py, static/video.js, templates/video.html
=> ENH: added comment logic

README.md
=> FIX: staging in roadmap changed to unchecked

.github/workflows/assign.yml
=> take action

.gitignore, crud/crud.py, main.py, static/video.css, templates/video.html
=> ENH: improved comment section

.github/workflows/assign.yml, .github/workflows/codeql-analysis.yml
=> BUG: Build Fixes

.github/workflows/build.yml, azure-pipelines.yml, jwt/jwt_utils.py, main.py, tests/test_main.py
=> ENH: added tests

azure-pipelines.yml
Added env variables to azure pipelines
=> ENH: added secrets az

azure-pipelines.yml, main.py
Quick fix for upload_file. 
Note: need to add tests
=> BUG: fixed upload file error

main.py, utils/utils.py
Fixed upload_file sanitize input and other security fixes
=> ENH: sec fix

docs/source/conf.py
=> :rocket: deploy readthedocs

.readthedocs.yaml
=> :wrench: Added readthedocs config

.readthedocs.yaml
=> :ambulance: read the docs fix

docs/source/index.rst, docs/source/main.rst, docs/source/modules.rst
=> added main autodoc

docs/source/conf.py, docs/source/modules.rst
=> :wrench: configuration sphinx added automock_import

static/styles.css, templates/video.html
=> :sparkles: Improved style for video.html

static/components/comment.js, static/components/like_dislike.js, static/video.css, templates/base.html, templates/video.html
=> :art: Improved style and structure of video.html with react

static/components/comment.js, static/script.js, static/video.css, static/video.js, templates/base.html, templates/index.html, templates/video.html
=> ❇️ Css improvements and relative timestamps 

.pylintrc, crud/crud.py, main.py, static/index.css, static/index.js, static/upload.css, static/upload.js, templates/index.html, templates/upload.html, tests/test_main.py
=> ❇️ Added Infinite Scroll and Video API 

jwt/jwt_utils.py
=> :bug: Fixed bug where invalid credentials for jwt token

static/profile.css
=> :art: Improved layout of profile.css

README.md, main.py
=> :memo: disabled docs url and added versioning

README.md
- Updated readme with techstack
=> :memo: updated techstack
